// Mirrors the canonical tag vocabulary in backend/app/services/recommendation_service.py
export const INTEREST_TAGS = [
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Cybersecurity",
  "Software Engineering",
  "Web Development",
  "Cloud Computing",
  "Finance",
  "Product Management",
  "Distributed Systems",
  "Predictive Healthcare",
  "Autonomous Systems",
  "DevOps",
  "Blockchain",
  "Game Development",
  "Augmented and Virtual Reality",
  "Computer Vision",
  "Natural Language Processing",
  "Generative AI",
  "High Performance Computing",
  "Digital Forensics",
  "Ethical Hacking",
  "UI/UX Design",
];

export const CAREER_GOALS = [
  "AI/ML Engineer",
  "Data Scientist",
  "Software Engineer",
  "Data Analyst",
  "Product Manager",
  "Research",
  "Finance/FinTech",
  "DevOps Engineer",
  "Game Developer",
  "Cybersecurity Analyst",
  "Blockchain Developer",
  "Robotics Engineer",
  "UX/Product Designer",
];
